fix: align openemr-cmd with google shell guide

diff --git a/utilities/openemr-cmd/openemr-cmd b/utilities/openemr-cmd/openemr-cmd
--- a/utilities/openemr-cmd/openemr-cmd
+++ b/utilities/openemr-cmd/openemr-cmd
@@ -32,31 +32,33 @@ DEV_TOOLS=/root/devtools
 
 check_docker_compose_install_or_not(){
 	DOCKER_COMPOSE_CODE=22
-	which docker-compose &>/dev/null
-	[ $? -ne 0 ] && echo "Please check docker-compose install or not." && exit $DOCKER_COMPOSE_CODE
+	if ! which docker-compose &>/dev/null; then
+		echo "Please check docker-compose install or not."
+		exit $DOCKER_COMPOSE_CODE
+	fi
 }
 
 quick_open_a_docker_shell(){
-  docker exec -w /var/www/localhost/htdocs/openemr -it $CONTAINER_ID sh
+  docker exec -w /var/www/localhost/htdocs/openemr -it "$CONTAINER_ID" sh
 }
 
 quick_open_a_maria_docker_shell(){
-  docker exec -it $MARIADB_CONTAINER_ID /bin/bash
+  docker exec -it "$MARIADB_CONTAINER_ID" /bin/bash
 }
 
 execute_command_flexible(){
 	if [ $# -lt 1 ]
 	then
 		echo "Please provide the command."
-		echo "e.g. `basename $0` [exec|e] \"tail -f /var/log/apache2/error.log\""
-		echo "e.g. `basename $0` -d docker_openemr-7-3-redis-312_1 [exec|e] \"tail -f /var/log/apache2/error.log\""
+		echo "e.g. $(basename "$0") [exec|e] \"tail -f /var/log/apache2/error.log\""
+		echo "e.g. $(basename "$0") -d docker_openemr-7-3-redis-312_1 [exec|e] \"tail -f /var/log/apache2/error.log\""
 	else
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$@"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$@"
 	fi
 }
 
 check_docker_log() {
-  docker logs $CONTAINER_ID
+  docker logs "$CONTAINER_ID"
 }
 
 check_docker_names() {
@@ -66,14 +68,14 @@ check_docker_names() {
 		# ARGS: couchdb php fhir mariadb mysql nginx openemr openldap orthanc redis.
 		echo '===Check the single Docker Name==='
 		echo '  STATUS        NAME'
-		docker ps -a --format "{{.Status}}\t{{.Names}}"| grep $CHECK_NAME
+		docker ps -a --format "{{.Status}}\t{{.Names}}"| grep "$CHECK_NAME"
 
 	else
 		# Show all the docker names.
 		echo '***************************************************************'
 		echo 'Show all the docker names by default.'
 		echo 'Please provide the keyword if you want to check the single one.'
-		echo "e.g `basename $0` [docker-names|dn] php"
+		echo "e.g $(basename "$0") [docker-names|dn] php"
 		echo '***************************************************************'
 		echo '=======Running Docker Names======='
 		docker ps | awk '{print $NF}'|grep -v NAMES|sort -n
@@ -101,7 +103,7 @@ creat_a_backup_snapshot(){
 		echo 'e.g. openemr-cmd [backup-snapshot|bs] example'
 		exit $BACKUP_FILE_CODE
 	else
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS backup $BACKUP_FILE"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS backup $BACKUP_FILE"
 	fi
 }
 
@@ -114,7 +116,7 @@ restore_from_a_snapshot(){
         echo 'e.g. openemr-cmd [restore-snapshot|rs] example'
         exit $BACKUP_FILE_CODE
     else
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS restore $BACKUP_FILE"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS restore $BACKUP_FILE"
 	fi
 }
 
@@ -132,9 +134,9 @@ copy_capsule_from_docker_to_host(){
 	else
 	  if [ -z "$BACKUP_HOST_DIR" ]
 	  then
-		  docker cp ${CONTAINER_ID}:/snapshots/$BACKUP_FILE .
+		  docker cp "${CONTAINER_ID}":/snapshots/"$BACKUP_FILE" .
     else
-      	  docker cp ${CONTAINER_ID}:/snapshots/$BACKUP_FILE "${BACKUP_HOST_DIR}/"
+      	  docker cp "${CONTAINER_ID}":/snapshots/"$BACKUP_FILE" "${BACKUP_HOST_DIR}/"
     fi
 	fi
 }
@@ -150,13 +152,12 @@ copy_capsule_from_host_to_docker(){
 		echo 'e.g. openemr-cmd [put-capsule|pc] example.tgz'
 		exit $BACKUP_FILE_CODE
 	else
-		ls $BACKUP_FILE  &>/dev/null
-		if [ $? -ne 0 ]
+		if ! ls "$BACKUP_FILE" &>/dev/null
 		then
 			echo 'Please check whether the capsule file exists or not'
 			exit $CP_CAP_DIR_DKR_CODE
 		else
-			docker cp $BACKUP_FILE  ${CONTAINER_ID}:/snapshots/
+			docker cp "$BACKUP_FILE" "${CONTAINER_ID}":/snapshots/
 		fi
 	fi
 }
@@ -171,7 +172,7 @@ ensure_current_ver_with_upgrade_ver(){
 		echo 'e.g. openemr-cmd [ensure-version|ev] 5.0.2'
 		exit $BACKUP_FILE_CODE
 	else
-    $DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS upgrade ${UPGRADE_FROM_VERSION}"
+    $DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS upgrade ${UPGRADE_FROM_VERSION}"
 	fi
 }
 
@@ -186,7 +187,7 @@ change_db_character_set_and_collation(){
 		echo '     openemr-cmd [encoding-collation|ec] utf8 utf8_general_ci'
 		exit $CHARACTER_SET_COLLATION_CODE
 	else
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS change-encoding-collation $1 $2"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS change-encoding-collation $1 $2"
 	fi
 }
 
@@ -199,7 +200,7 @@ setup-client-cert(){
         echo 'e.g. openemr-cmd [scc|setup-client-cert] sll'
         exit $CERT_PACKAGE_CODE
     else
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS setup-client-cert $CERT_PACKAGE"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS setup-client-cert $CERT_PACKAGE"
 	fi
 }
 
@@ -214,13 +215,12 @@ put-client-cert(){
 		echo 'e.g. openemr-cmd [pcc|put-client-cert] sll.zip'
 		exit $CERT_PACKAGE_FILE_CODE
 	else
-		ls $CERT_PACKAGE_FILE &>/dev/null
-		if [ $? -ne 0 ]
+		if ! ls "$CERT_PACKAGE_FILE" &>/dev/null
 		then
 			echo 'Please check whether the certificate package file exists or not'
 			exit $PUT_CLIENT_CERT_CODE
 		else
-			docker cp $CERT_PACKAGE_FILE ${CONTAINER_ID}:/certs/
+			docker cp "$CERT_PACKAGE_FILE" "${CONTAINER_ID}":/certs/
 		fi
 	fi
 }
@@ -228,31 +228,31 @@ put-client-cert(){
 import-random-patients(){
   if [ $# == 2 ]
   then
-    $DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS import-random-patients $1 $2"
+    $DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS import-random-patients $1 $2"
   else
-    $DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS import-random-patients $1"
+    $DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS import-random-patients $1"
   fi
 }
 
 register-oauth2-client-demo(){
-  $DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS register-oauth2-client-demo $1"
+  $DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS register-oauth2-client-demo $1"
 }
 
 register-oauth2-client(){
   if [ $# == 1 ]
   then
-    $DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS register-oauth2-client $1"
+    $DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS register-oauth2-client $1"
   else
-    $DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS register-oauth2-client"
+    $DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS register-oauth2-client"
   fi
 }
 
 set-swagger-to-multisite(){
     if [ $# == 1 ]
     then
-      $DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS set-swagger-to-multisite $1"
+      $DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS set-swagger-to-multisite $1"
     else
-      $DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS set-swagger-to-multisite"
+      $DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS set-swagger-to-multisite"
     fi
 }
 
@@ -261,11 +261,11 @@ set-webroot(){
     then
       # assume the openemr parameter was given, so set openemr webroot
       echo "changing webroot to openemr"
-      $DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "sed -i 's@^DocumentRoot /var/www/localhost/htdocs.*@DocumentRoot /var/www/localhost/htdocs@g' /etc/apache2/conf.d/openemr.conf"
+      $DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "sed -i 's@^DocumentRoot /var/www/localhost/htdocs.*@DocumentRoot /var/www/localhost/htdocs@g' /etc/apache2/conf.d/openemr.conf"
     else
       # set to blank, so set blank webroot
       echo "changing webroot to blank"
-      $DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "sed -i 's@^DocumentRoot /var/www/localhost/htdocs.*@DocumentRoot /var/www/localhost/htdocs/openemr@g' /etc/apache2/conf.d/openemr.conf"
+      $DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "sed -i 's@^DocumentRoot /var/www/localhost/htdocs.*@DocumentRoot /var/www/localhost/htdocs/openemr@g' /etc/apache2/conf.d/openemr.conf"
     fi
     # restart the docker
     echo "restarting openemr docker so the apache configuration change will take effect"
@@ -276,9 +276,9 @@ docker-pull-image(){
     docker_images=$(docker ps --format "table {{.Image}}")
     for IMAGE in $docker_images
     do
-    if [ $IMAGE != "IMAGE" ] 
+    if [ "$IMAGE" != "IMAGE" ] 
     then
-      read -e -p "Do you wish to pull $IMAGE ? (y) " RESP
+      read -r -e -p "Do you wish to pull $IMAGE ? (y) " RESP
       if [ "$RESP" = "y" ]; then 
         docker pull "$IMAGE";
       else 
@@ -294,15 +294,17 @@ FINAL_EXIT_CODE=0
 
 # Confirm the docker install or not.
 DOCKER_CODE=16
-which docker &>/dev/null
-[ $? -ne 0 ] && echo "Please check docker install or not." && exit $DOCKER_CODE
+if ! which docker &>/dev/null; then
+  echo "Please check docker install or not."
+  exit $DOCKER_CODE
+fi
 
 # Script usage.
 if [ $# -eq 0 ] || [ "$FIRST_ARG" == '--help' ] || [ "$FIRST_ARG" == '-h' ]
 then
   echo ""
-  echo "Usage: `basename $0` COMMAND [ARGS]"
-  echo "Usage: `basename $0` -d <docker name> COMMAND [ARGS]"
+  echo "Usage: $(basename "$0") COMMAND [ARGS]"
+  echo "Usage: $(basename "$0") -d <docker name> COMMAND [ARGS]"
   echo "Options:"
   echo "  -h, --help                         Show the commands usage"
   echo "  -v, --version                      Show the openemr-cmd command version"
@@ -408,11 +410,11 @@ fi
 
 # Specify the docker id/name to execute the commands.
 #  default to insane dev docker, if exists
-CONTAINER_ID=$(docker ps | grep $INSANE_DEV_DOCKER | cut -f 1 -d " ")
-if [ -z $CONTAINER_ID ]
+CONTAINER_ID=$(docker ps | grep "$INSANE_DEV_DOCKER" | cut -f 1 -d " ")
+if [ -z "$CONTAINER_ID" ]
 then
   # else, default to easy dev docker, if exists
-  CONTAINER_ID=$(docker ps | grep $EASY_DEV_DOCKER | cut -f 1 -d " ")
+  CONTAINER_ID=$(docker ps | grep "$EASY_DEV_DOCKER" | cut -f 1 -d " ")
 fi
 # override the default container setting if supplied via the -d parameter
 #  (also removing no longer needed parameters via shift)
@@ -432,10 +434,10 @@ else
 fi
 
 #collect the couchdb docker name
-COUCHDB_CONTAINER=$(docker ps | grep $COUCHDB_DOCKER | cut -f 1 -d " ")
+COUCHDB_CONTAINER=$(docker ps | grep "$COUCHDB_DOCKER" | cut -f 1 -d " ")
 
 # Collect the mariadb container id
-MARIADB_CONTAINER_ID=$(docker ps | grep $MARIADB_DOCKER | cut -f 1 -d " ")
+MARIADB_CONTAINER_ID=$(docker ps | grep "$MARIADB_DOCKER" | cut -f 1 -d " ")
 
 # See how we were called.
 # For the shift usage, it used to cover the insane env.
@@ -518,168 +520,168 @@ case "$FIRST_ARG" in
     quick_open_a_maria_docker_shell
 		;;
 	bt)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS build-themes"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS build-themes"
 		;;
 	pl)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS php-log"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS php-log"
 		;;
 	pr)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS psr12-report"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS psr12-report"
 		;;
 	pf)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS psr12-fix"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS psr12-fix"
 		;;
 	ltr)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS lint-themes-report"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS lint-themes-report"
 		;;
 	ltf)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS lint-themes-fix"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS lint-themes-fix"
 		;;
 	ljr)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS lint-javascript-report"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS lint-javascript-report"
 		;;
 	ljf)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS lint-javascript-fix"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS lint-javascript-fix"
 		;;
 	pp)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS php-parserror"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS php-parserror"
 		;;
 	ut)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS unit-test"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS unit-test"
 		;;
 	jut)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS javascript-unit-test"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS javascript-unit-test"
 		;;
 	jrb)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS jut-reports-build"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS jut-reports-build"
 		;;
 	at)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS api-test"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS api-test"
 		;;
 	et)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS e2e-test"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS e2e-test"
 		;;
 	st)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS services-test"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS services-test"
 		;;
 	ft)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS fixtures-test"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS fixtures-test"
 		;;
 	vt)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS validators-test"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS validators-test"
 		;;
 	ct)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS controllers-test"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS controllers-test"
 		;;
 	ctt)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS common-test"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS common-test"
 		;;
 	cs)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS clean-sweep"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS clean-sweep"
 		;;
 	cst)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS clean-sweep-tests"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS clean-sweep-tests"
 		;;
 	dr)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS dev-reset"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS dev-reset"
 		restart_couchdb_docker
 		;;
 	di)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS dev-install"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS dev-install"
 		restart_couchdb_docker
 		;;
 	dri)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS dev-reset-install"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS dev-reset-install"
 		restart_couchdb_docker
 		;;
 	drid)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS dev-reset-install-demodata"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS dev-reset-install-demodata"
 		restart_couchdb_docker
 		;;
 	ls)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS list-snapshots"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS list-snapshots"
 		;;
 	lc)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS list-capsules"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS list-capsules"
 		;;
 	em)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS enable-multisite"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS enable-multisite"
 		;;
 	dm)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS disable-multisite"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS disable-multisite"
 		;;
 	fh)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS force-https"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS force-https"
 		;;
 	ufh)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS un-force-https"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS un-force-https"
 		;;
 	ossc)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS on-self-signed-cert"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS on-self-signed-cert"
 		;;
 	lcc)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS list-client-certs"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS list-client-certs"
 		;;
 	ss)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS sql-ssl"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS sql-ssl"
 		;;
 	sso)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS sql-ssl-off"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS sql-ssl-off"
 		;;
 	ssc)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS sql-ssl-client"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS sql-ssl-client"
 		;;
 	ssco)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS sql-ssl-client-off"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS sql-ssl-client-off"
 		;;
 	css)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS couchdb-ssl"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS couchdb-ssl"
 		;;
 	cso)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS couchdb-ssl-off"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS couchdb-ssl-off"
 		;;
 	csc)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS couchdb-ssl-client"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS couchdb-ssl-client"
 		;;
 	csco)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS couchdb-ssl-client-off"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS couchdb-ssl-client-off"
 		;;
 	lss)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS ldap-ssl"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS ldap-ssl"
 		;;
 	lso)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS ldap-ssl-off"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS ldap-ssl-off"
 		;;
 	lsc)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS ldap-ssl-client"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS ldap-ssl-client"
 		;;
 	lsco)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS ldap-ssl-client-off"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS ldap-ssl-client-off"
 		;;
 	gmb|generate-multisite-bank)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS generate-multisite-bank $@"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS generate-multisite-bank $*"
 		;;
 	el)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS enable-ldap"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS enable-ldap"
 		;;
 	dld)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS disable-ldap"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS disable-ldap"
 		;;
 	xl)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS xdebug-log"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS xdebug-log"
 		;;
 	lxp)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS list-xdebug-profiles"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS list-xdebug-profiles"
 		;;
 	bad)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS build-api-docs"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS build-api-docs"
 		;;
 	lm)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS list-multisites"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS list-multisites"
 		;;
 
 	*)
-		$DOCKER_EXEC_CMD $CONTAINER_ID $SHELL_TYPE "$DEV_TOOLS $FIRST_ARG"
+		$DOCKER_EXEC_CMD "$CONTAINER_ID" "$SHELL_TYPE" "$DEV_TOOLS $FIRST_ARG"
 		;;
 esac
 exit $FINAL_EXIT_CODE
